### ISSUE TITLE
Potentially use the spin_loop_hint

### ISSUE THREAD

**Issue by CryZe** [alexheretic/spin-sleep#1]
https://doc.rust-lang.org/std/sync/atomic/fn.spin_loop_hint.html

I'm not sure if it helps save energy and if it causes some problems. But it may be worth looking into.

**Comment by alexheretic** [comment]
Thank you for pointing this out! I will investigate this week.

**Comment by alexheretic** [comment]
I ran a test where I record the average number of spins and actual wait duration on a range of short sleep times _(no thread::sleep usage)_.

# Linux
Requested Duration | Spins | Actual Duration
---|---|---
5ms | 10070 | 5000497ns
5ms { spin_loop_hint } | 7741 | 5000544ns
5ms { yield_now } | 755 | 5001114ns
5ms { spin_loop_hint + yield_now } | 735 | 5001145ns
900µs | 33828 | 900103ns
900µs { spin_loop_hint } | 26304 | 900208ns
900µs { yield_now } | 2747 | 900377ns
900µs { spin_loop_hint + yield_now } | 2667 | 900394ns
5µs | 194 | 5121ns
5µs { spin_loop_hint } | 152 | 5115ns
5µs { yield_now } | 16 | 5171ns
5µs { spin_loop_hint + yield_now } | 16 | 5331ns
100ns | 4 | 214ns
100ns { spin_loop_hint } | 3 | 192ns
100ns { yield_now } | 1 | 421ns
100ns { spin_loop_hint + yield_now } | 1 | 467ns

# Windows
Requested Duration | Spins | Actual Duration
---|---|---
5ms | 8000 | 5014428ns
5ms { spin_loop_hint } | 5544 | 5023310ns
5ms { yield_now } | 1213 | 5005125ns
5ms { spin_loop_hint + yield_now } | 1276 | 5017571ns
900µs | 21861 | 900265ns
900µs { spin_loop_hint } | 19279 | 900326ns
900µs { yield_now } | 4044 | 900478ns
900µs { spin_loop_hint + yield_now } | 3441 | 900403ns
5µs | 124 | 5156ns
5µs { spin_loop_hint } | 109 | 5200ns
5µs { yield_now } | 23 | 5215ns
5µs { spin_loop_hint + yield_now } | 22 | 5183ns
100ns | 5 | 301ns
100ns { spin_loop_hint } | 5 | 301ns
100ns { yield_now } | 1 | 325ns
100ns { spin_loop_hint + yield_now } | 1 | 358ns

From this I conclude that Linux & Windows benefit from `spin_loop_hint` and from `yield_now` without much accuracy cost. 

I think I'll simply add `std::thread::yield_now` to the spin loop, as it has a dramatic effect on spin count.

**Comment by alexheretic** [comment]
This is now available in `0.3.5`, thanks again!
