### ISSUE TITLE
LoopHelper accumulates lag

### ISSUE THREAD

**Issue by timstr** [alexheretic/spin-sleep#10]
Using `LoopHelper`, when one loop iteration takes slightly longer than expected, the resulting lag accumulates rather than shortening the next loop iteration accordingly. This causes the average frame rate to be biased towards being slower, and for situations requiring work to be done at a very precise rate (e.g. audio callbacks), this can lead to regularly missed deadlines.

In the following simplified example from my audio project, using `LoopHelper` in what seems like the obvious way causes the loop to run more slowly than expected over time, leading to audio dropouts.
```rust
let frame_duration = Duration::from_micros((1_000_000.0 / frames_per_sec) as u64);

let mut loop_helper = LoopHelper::builder()
    .build_with_target_rate(frames_per_sec);

loop {
    let delta = loop_helper.loop_start();
    if delta > frame_duration {
        println!("WARNING: missed a deadline");
    }
    self.process_next_audio_frame();
    loop_helper.loop_sleep();
}
```

If I stop using `LoopHelper` and instead do a bit of book-keeping to ensure uniformity, then the loop runs at precisely the right rate, and there are no more audio dropouts.
```rust
let mut deadline = Instant::now() + frame_duration;

loop {
    self.process_next_audio_frame();
    let now = Instant::now();
    let delta = deadline.duration_since(now);
    if now > deadline {
        println!("WARNING: missed a deadline");
    } else {
        let delta = deadline.duration_since(now);
        spin_sleep::sleep(delta);
    }
    deadline += frame_duration;
}
```

Admittedly, this might not be one of the design goals of `LoopHelper` and that's fine by me. However, I think this use case is probably common, and it would be nice to have it supported directly by something like `LoopHelper`.

Some suggestions:
 - Add a warning to the `LoopHelper` documentation that it accumulates lag and doesn't guarantee uniformity over time
 - Add an option to `LoopHelper` such as `set_uniformity()` that causes it to behave like in the second code example, by sleeping until a uniformly-spaced deadline is met
 - Add a different helper, such as `UniformLoopHelper` to make the implementations cleaner

Thank you for your consideration. Let me know if you'd like me to draft some changes and make a pull request.

**Comment by alexheretic** [comment]
Thanks for the explanation of your use case. `LoopHelper` was designed to be a frame rate limiter. When you have a frame rate limit it is an upper bound. You wouldn't expect the limiter to try to run faster than the limit because is had been slower for a while.

I'd say it's definitely worth clarifying the docs about this. 

It's probably simplest to just have your own helper (that perhaps uses _spin-sleep_ sleep) that behaves as you require outside of this crate. On the other hand it might be worth having a `UniformLoopHelper` here if there are others that that would help.

**Comment by recatek** [comment]
+1 for a `UniformSleepHelper`. I've also run into this issue for trying to get a consistent update frequency. Currently the workaround is to add a second phase of spinning to correct for inaccuracy in the loop helper.

**Comment by alexheretic** [comment]
See https://github.com/alexheretic/spin-sleep/issues/5#issuecomment-1869884926 related to LoopHelper api future.

**Comment by alexheretic** [comment]
#19
