### ISSUE TITLE
Not calling loop_helper::report_rate will cause internal panic

### ISSUE THREAD

**Issue by SquareMan** [alexheretic/spin-sleep#14]
Every time `loop_helper::loop_start` is called, `delta_count` is incremented by one. This eventually results in an integer overflow panic if `loop_helper::report_rate` is not used. This feels wrong to me, as you may not always care about checking the rate. Additionally it can be a difficult error to catch if you're testing session is short, as it takes some time for the delta value to accumulate.

If this behavior is actually intended, I think it should at least be documented somewhere on `LoopHelper`.

**Comment by alexheretic** [comment]
Thanks yes good spot. It indeed was not my intention to panic after looping 4294967295 times without calling `LoopHelper::report_rate`.

I'll change this increment to be explicit wrapping. Note --release builds use wrapping add by default so wouldn't generally be affected.
