### ISSUE TITLE
Use Windows WaitableTimer with high resolution if available

### ISSUE THREAD

**Issue by terrorfisch** [alexheretic/spin-sleep#16]
Windows introduced a flag to create a "high resolution" timer in Windows 10, version 1803. On my system I can get 500µs resolution with it without fiddling with `timeBeginPeriod`.

 https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createwaitabletimerexw

**Comment by alexheretic** [comment]
Seems promising. We'll need to look into:
* How to query if the OS is Windows 10 version 1803, where we expect this to work.
* How to actually sleep using this with rust code (not immediately obvious to me at least).
* Also maybe switching this crate to https://github.com/microsoft/windows-rs.

**Comment by alexheretic** [comment]
Rust 1.75.0 std [now does this](https://github.com/rust-lang/rust/pull/116461).

What's missing is for spin-sleep to detect at runtime if the Windows version actually supports this (if not we can fallback to current 1ms behaviour).

To do this i think we can try once to create a high res timer and use the success/fail of that call to indicate support. If supported, and on rust >= 1.75 we can use std::thread::sleep with a much tighter accuracy configured. I'll run some tests to find a decent default accuracy for high-res win timers.

As this relies on compilation with rust 1.75 this should become the min rust-version (even though the existing policy is latest stable, we want a stronger indication that 1.75 must be used).

**Comment by alexheretic** [comment]
Alternatively we could just do the sleeping using the windows api and we wouldn't have any particular requirement on rust version, which may be nicer overall.
