### ISSUE TITLE
Since 4.8, Linux's timer wheel has input-dependent precision

### ISSUE THREAD

**Issue by eternaleye** [alexheretic/spin-sleep#2]
In version 4.8 of the Linux kernel, Thomas Gleixner's [rewrite](https://lwn.net/Articles/646950/) of the Linux timer wheel was merged. The rewritten timer wheel buckets timers based on how far in the future they are, and each bucket has a corresponding level of precision. To quote the article:

> The end result is that the timer events in the higher-level arrays will be expired in place, rather than being cascaded downward. This approach, obviously, saves all the effort of performing the cascade. But it also means that any timeout that is more than 31 jiffies in the future will be run with lower accuracy. For example, a timeout that is 36 jiffies in the future will be put in the next higher eight-jiffy slot — 40 jiffies in the future. So that event will expire four jiffies later than requested. As timeouts are placed further into the future, the accuracy of their expiration will decline accordingly. The seventh level in this scheme will hold timeouts that are at least 1,048,576 jiffies in the future with 262,144-jiffy resolution. On a 1000HZ system, that corresponds to timeouts at least 17 minutes in the future; they will expire with a resolution of four minutes.

As a result, on post-4.8 systems, both the kernel's configured tick rate (`CONFIG_HZ`) _and the actual duration of sleep requested_ must be known in order to predict "how far `sleep(2)` can be trusted".

**Comment by eternaleye** [comment]
As a corollary, however, on such systems it would be possible to perform a shorter `sleep(2)` after a longer `sleep(2)` in order to get closer to the point where the syscall can't be trusted.

**Comment by alexheretic** [comment]
So perhaps we could calculate a more intelligent sleep accuracy for linux from the kernel _HZ_. The delay is a little more volatile still though as repeated calls are potentially made to _nanosleep_  to handle signal interrupts.

I think this jiffy stuff only applies when a HRT is unavailable though, and I pretty much expect to have one. 

>   Before Linux 2.6.21, the accuracy of timer and sleep system calls
  (see below) was also limited by the size of the jiffy.
>
>  Since Linux 2.6.21, Linux supports high-resolution timers (HRTs),
  optionally configurable via CONFIG_HIGH_RES_TIMERS.  On a system that
  supports HRTs, the accuracy of sleep and timer system calls is no
  longer constrained by the jiffy, but instead can be as accurate as
  the hardware allows (microsecond accuracy is typical of modern
  hardware).  You can determine whether high-resolution timers are
  supported by checking the resolution returned by a call to
  clock_getres(2) or looking at the "resolution" entries in
  /proc/timer_list.
>
>  HRTs are not supported on all hardware architectures.  (Support is
  provided on x86, arm, and powerpc, among others.)

A simple improvement would be to detect if no HRTs are available and use a much longer accuracy setting on unix. However, I'd probably only bother adding this if we had an example platform that this actually applied to.
