### ISSUE TITLE
No substitute for delta time in spin_sleep_util

### ISSUE THREAD

**Issue by jordan4ibanez** [alexheretic/spin-sleep#26]
If this is wrong, please guide me in the right direction. I have been looking for the reporter that tells the current delta time of the loop, but I cannot seem to find it in spin_sleep_util.

**Comment by alexheretic** [comment]
`LoopHelper::loop_start` returned the elapsed duration since the last call.

You can replace that by saving the last_loop time yourself.
```rust
let mut last_loop = Instant::now();
loop {
    let delta = {
        let delta = last_tick.elapsed();
        last_tick = Instant::now();
        delta
    };
    ...
}

**Comment by jordan4ibanez** [comment]
This would be very helpful as a tutorial actually.

**Comment by jordan4ibanez** [comment]
I made this thing ```rust
use std::time::Instant;

///
/// DeltaTime is a micro struct which encapsulates logic
/// for tracking the delta time between loop ticks.
///
pub struct DeltaReporter {
  old_time: Instant,
}

impl DeltaReporter {
  pub fn new() -> Self {
    DeltaReporter {
      old_time: Instant::now(),
    }
  }

  ///
  /// Get the time in seconds as f64 since the last loop.
  ///
  pub fn report(&mut self) -> f64 {
    let delta = self.old_time.elapsed().as_secs_f64();
    self.old_time = Instant::now();
    delta
  }
}
```
if you want it, you can have it!

**Comment by alexheretic** [comment]
I don't think we need an API for this in _spin_sleep_util_ it's pretty much already there with std.

Actually it occurs to me now it's slightly more efficient (avoids the `now()` call inside `elapsed()`) and doesn't "lose" any nanos if you do it this way:
```rust
let mut last_loop = Instant::now();
loop {
    let delta = {
        let now = Instant::now();
        let delta = now.duration_since(last_loop);
        last_loop = now;
        delta
    };
    ...
}
```

For fun, instead of an API wrapper another option is to use an extension trait:

```rust
trait InstantExt {
    /// Set self to now and return the duration since the last call.
    fn advance_to_now(&mut self) -> Duration;
}
impl InstantExt for Instant {
    fn advance_to_now(&mut self) -> Duration {
        let now = Instant::now();
        let delta = now.duration_since(*self);
        *self = now;
        delta
    }
}
```
Usage:
```rust
let mut last_loop = Instant::now();
loop {
    let delta = last_loop.advance_to_now();
    ...
}
```
Or indeed `advance_to_now().as_secs_f64()`. 

But I'll close this ticket now as I don't intend to make any changes to the spin-sleep crates.

**Comment by jordan4ibanez** [comment]
Thanks for the micro opt and thanks for the project! I'll implement that into the code and you have a great day.
