### ISSUE TITLE
Document the implementation details (and consequences) in relation to the O/S

### ISSUE THREAD

**Issue by saveriomiroddi** [alexheretic/spin-sleep#7]
Hi there!

I was looking at this project, since it's referenced from [another one](https://github.com/amethyst/amethyst/issues/2083).

Now, I had a look at the source code, but I'm confused.

The project is named "spin" loop, which I think it's not accurate, as the library actually yields the current thread after the sleep (as opposed to the conventional implementation of using a pause intrinsic).

Now, while this may be considered a pedantic semantic argument, it has practical consequences in the context of the running operating system.

Specifically, what are the performance characteristics on Linux? Assuming that `thread::yield_now()` invokes [`sched_yield`](https://www.man7.org/linux/man-pages/man2/sched_yield.2.html), specific conditions are required, which I don't see referenced neither in the code nor the documentation:

> sched_yield() is intended for use with real-time scheduling
> policies (i.e., SCHED_FIFO or SCHED_RR).  Use of sched_yield()
> with nondeterministic scheduling policies such as SCHED_OTHER is
> unspecified and very likely means your application design is
> broken.

AFAIK, `SCHED_OTHER` is the default scheduler; on my system, right now, out of ~2100 threads, approximately 2000 are `SCHED_OTHER` and 5 `SCHED_RR`.

Reconnecting to the spin loop argument, a conventional spin loop would be O/S-independent (as there would be no scheduler call).

Now, independently of the above argument, I think it is important to document these details (and the related implementation choices), since this is a very technical library, and projects may be significantly affected - even if the yielding strategy had inherent problems.

**Comment by alexheretic** [comment]
I investigated yield_now & spin_loop_hint back in https://github.com/alexheretic/spin-sleep/issues/1#issuecomment-372304712 and concluded yield_now had the best characteristics.

I have no problem with making the docs clearer regarding this usage.

**Comment by saveriomiroddi** [comment]
> I investigated yield_now & spin_loop_hint back in [#1 (comment)](https://github.com/alexheretic/spin-sleep/issues/1#issuecomment-372304712) and concluded yield_now had the best characteristics.
> 
> I have no problem with making the docs clearer regarding this usage.

Wow, that level of performance is very surprising, actually, so surprising, that I don't know how to exactly deal with it :grimacing: (I'm exploring different strategies for gaming engine purposes).

I think adding a mention to the README about the numbers (maybe copying them to a wiki page, or having them in a README section) would be of great interest for people using this crate.

Over the next couple of weeks I'm going to do some more in-depth investigatation. I find the thread yielding strategy surprisingly fast, so something interesting must be going on :smile:.

Thanks for your fast reply :smile:

**Comment by saveriomiroddi** [comment]
Hi there!

I'm closing the issue, as I've done a fair bit of research and experimentation and I don't personally need more documentation (although of course, extending the existing one is a good idea) :) I've written about the experimentation and the results in the referenced issue.

Thanks for you work :)
